### ISSUE TITLE
Cannot terminate the process

### ISSUE THREAD

**Issue by B3J4y** [wetransform-os/ProMCDA#27] opened 2024-02-02 07:57 UTC
After running the toy example, the process did not finish, and I was unable to terminate it properly.

**Comment by Flaminietta** [comment] 2024-03-15 13:09
Dear @B3J4y, in the main branch, latest commit e071d84, the toy example runs and finishes as expected for me.
<img width="1410" alt="Screenshot 2024-03-15 at 14 08 41" src="https://github.com/wetransform-os/ProMCDA/assets/26147427/0b244d96-eb25-41d0-ac96-2bfca24be293">

If you can also try again and confirm that now everything is fine, I can then close this issue. Thank you!

**Comment by B3J4y** [comment] 2024-06-27 10:58
Sorry, the problem is still there:  
![ProMCMA](https://github.com/wetransform-os/ProMCDA/assets/1398738/0870a3fb-885f-4ed2-a715-5af36e351527)

I left it open for a while to look if there was a calculation which needs some time, but this process doesn't come back.

I use windows.

**Comment by mspada** [comment] 2024-07-02 08:50
@B3J4y I run the test on windows at it works smooth. Just a question: did the figures open on your browser or not? If not it might be a problem with some close ports that do not allow plotly to open the figures and, therefore, not ending the process. Let us know!

**Comment by B3J4y** [comment] 2024-07-08 14:44
There are 2 figures. I append the open images:
![Figure1](https://github.com/wetransform-os/ProMCDA/assets/1398738/e77353c4-7c9d-4bb5-880b-b682003714e7)
![Figure2](https://github.com/wetransform-os/ProMCDA/assets/1398738/53ae44d7-95ff-40b6-b93e-e763a2be5006)

**Comment by mspada** [comment] 2024-07-08 16:07
@B3J4y Thank you! Therefore, there might be some issue with the saving of some of the output files.  When you run it, is it saving some output files in the output directory or not? If yes, what output files is ProMCDA saving?

**Comment by B3J4y** [comment] 2024-07-09 06:16
You're welcome. It is tough to fix bugs remotely on another machine without having direct access. Hopefully, we can manage this.

Here is an image of the output folder:

![Output_files](https://github.com/wetransform-os/ProMCDA/assets/1398738/45c331c2-11fc-4985-bfa7-8b94e6eec301)

**Comment by mspada** [comment] 2024-07-09 06:23
Perfect, thanks! I know this is quite a tough way to try to fix an issue. In any case, it looks like that the issue is related to the figures, probably in the saving of them in the output folder. I'll have a look at it. I'll keep you posted

**Comment by mspada** [comment] 2024-07-10 08:31
@B3J4y I guess I found the issue. It looks like that it is related to kaleido, which is used to save the static image of the plotly plots. In some cases (only on windows and not for everyone) the new version of kaleido (0.2.1), which is used in ProMCDA, is not correctly working. To solve this the community propose to downgrade kaleido to the version 0.1.0.post1 as discussed in https://community.plotly.com/t/static-image-export-hangs-using-kaleido/61519 and https://github.com/plotly/Kaleido/issues/126
Could you please try to downgrade kaleido to the version 0.1.0.post1 and run the test once again?

**Comment by B3J4y** [comment] 2024-07-23 20:10
@mspada Thank you for finding the solution. I haven't had the time to downgrade Kaleido, and I feel that whether it works or not, your package will be very weak in terms of reusability if it relies on this mechanism for your Windows users. Could you possibly package it into a Docker container and add a Dockerfile to the repository? This could solve the Windows problems and provide users with a system-independent way to run the software.

**Comment by Flaminietta** [comment] 2024-07-30 18:06
Dear @B3J4y, your request is addressed in [this PR](https://github.com/wetransform-os/ProMCDA/pull/46) (ProMCDA is now also dockerized).

**Closed by Flaminietta** 2024-07-30 18:06 UTC
Labels: bug, joss review related
